"""remove_vector_dim_constraint

Revision ID: 6753009576a3
Revises: 1b81686b07e3
Create Date: 2026-07-23 15:58:39.228135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6753009576a3'
down_revision: Union[str, Sequence[str], None] = '1b81686b07e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE vector_embeddings ALTER COLUMN embedding TYPE vector;")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE vector_embeddings ALTER COLUMN embedding TYPE vector(1024);")
    # ### end Alembic commands ###
